import type { CSSProperties } from "react";

/** Co-located styles for the SkillCard left-list row. */
export const s = {
  card: (active: boolean, enabled: boolean): CSSProperties => ({
    padding: 12,
    borderRadius: 8,
    cursor: "pointer",
    border: "1px solid " + (active ? "var(--border-strong)" : "var(--border)"),
    background: active ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: enabled ? 1 : 0.6,
  }),
  headerRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  iconBox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  name: {
    fontSize: 13,
    fontWeight: 600,
    flex: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  deleteBtn: (busy: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    cursor: busy ? "not-allowed" : "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
    padding: 3,
  }),
  description: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    margin: "7px 0",
    lineHeight: 1.4,
    display: "-webkit-box",
    WebkitLineClamp: 1,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  source: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  stats: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    marginTop: 9,
    fontSize: 11.5,
  } satisfies CSSProperties,
  statStrong: { color: "var(--text-secondary)", fontWeight: 600 } satisfies CSSProperties,
  statMuted: { color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
