import type { CSSProperties } from "react";

/** Co-located styles for the agent Context tab. */
export const s = {
  wrap: { padding: 28, maxWidth: 900 } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  heading: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", margin: "0 0 16px" } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 8px",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    marginBottom: 8,
  } satisfies CSSProperties,
  rowPath: { fontSize: 13, fontWeight: 600, flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowName: { fontSize: 13, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  rowDir: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  rowTokens: { fontSize: 12.5, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  filterInput: {
    fontSize: 13,
    padding: "7px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    outline: "none",
    width: 200,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 18,
    paddingTop: 16,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  total: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  injectionLabel: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  overBudget: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--crit)",
    background: "var(--crit-bg, transparent)",
    border: "1px solid var(--crit)",
    borderRadius: 7,
    padding: "6px 10px",
    marginTop: 10,
  } satisfies CSSProperties,
  budgetOk: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  manifestSection: { marginTop: 18 } satisfies CSSProperties,
  manifestLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 8px",
  } satisfies CSSProperties,
  manifestBlock: {
    fontSize: 12.5,
    lineHeight: 1.7,
    padding: "12px 14px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  manifestHeading: { color: "var(--text-primary)", fontWeight: 600 } satisfies CSSProperties,
  manifestPath: { color: "var(--text-muted)" } satisfies CSSProperties,
  manifestEmpty: { color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
} as const;
